/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j_auto;

/**
 *
 * @author Adeotun
 */
public class autoFrame extends javax.swing.JFrame {

    /**
     * Creates new form autoFrame
     */
    public autoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oilchange = new javax.swing.JCheckBox();
        lubejob = new javax.swing.JCheckBox();
        radflush = new javax.swing.JCheckBox();
        transflush = new javax.swing.JCheckBox();
        inspection = new javax.swing.JCheckBox();
        mufflerrep = new javax.swing.JCheckBox();
        tirerotation = new javax.swing.JCheckBox();
        calculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oilchange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        oilchange.setText("Oil change --N26.00");
        oilchange.setActionCommand("26");

        lubejob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lubejob.setText("Lube job --N18.00");
        lubejob.setActionCommand("18");

        radflush.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radflush.setText("Radiator flush --N30.00");
        radflush.setActionCommand("30");

        transflush.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transflush.setText("Transmission Flush --N80.00");
        transflush.setActionCommand("80");

        inspection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inspection.setText("Inspection --N15.00");
        inspection.setActionCommand("15");

        mufflerrep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mufflerrep.setText("Muffler Replacement --N100.00");
        mufflerrep.setActionCommand("100");

        tirerotation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tirerotation.setText("Tire rotation --N20.00");
        tirerotation.setActionCommand("20");

        calculate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        calculate.setText("Calculate Total");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total :");

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oilchange)
                    .addComponent(lubejob)
                    .addComponent(radflush)
                    .addComponent(transflush))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mufflerrep)
                    .addComponent(tirerotation)
                    .addComponent(inspection)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oilchange)
                    .addComponent(inspection))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lubejob)
                    .addComponent(mufflerrep))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radflush)
                    .addComponent(tirerotation))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transflush)
                    .addComponent(jLabel1)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        int i = 0;
        int l = 0;
        int m = 0;
        int o = 0;
        int r = 0;
        int t = 0;
        int tf = 0;
        if (inspection.isSelected() == true){
            i = Integer.parseInt(inspection.getActionCommand());
        }
        if (lubejob.isSelected() == true){
            l = Integer.parseInt(lubejob.getActionCommand());
        }
        if (mufflerrep.isSelected() == true){
            m = Integer.parseInt(mufflerrep.getActionCommand());
        }
        if (oilchange.isSelected() == true){
            o = Integer.parseInt(oilchange.getActionCommand());
        }
        if (radflush.isSelected() == true){
            r = Integer.parseInt(radflush.getActionCommand());
        }
        if (tirerotation.isSelected() == true){
            t = Integer.parseInt(tirerotation.getActionCommand());
        }
        if (transflush.isSelected() == true){
            tf = Integer.parseInt(transflush.getActionCommand());
        }
        int mysum = i+l+m+o+r+t+tf;
        total.setText("=N="+String.valueOf(mysum));
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(autoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(autoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(autoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(autoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new autoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JCheckBox inspection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox lubejob;
    private javax.swing.JCheckBox mufflerrep;
    private javax.swing.JCheckBox oilchange;
    private javax.swing.JCheckBox radflush;
    private javax.swing.JCheckBox tirerotation;
    private javax.swing.JLabel total;
    private javax.swing.JCheckBox transflush;
    // End of variables declaration//GEN-END:variables
}
